language: node_js
node_js:
  - "7"
  - "8"
addons:
  code_climate:
    repo_token: 9c49e40b0c6ffbbcc0a531c5a183fc6ad129ccb3036f0584c97f2c3289254adb
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info